# Generated by Django 5.2.16 on 2026-07-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("pic_url", models.URLField(blank=True, max_length=500)),
                ("intro", models.TextField(blank=True)),
                ("origin_url", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("artist_names", models.CharField(max_length=500)),
                ("lyric", models.TextField(blank=True)),
                ("cover_url", models.URLField(max_length=500)),
                ("origin_url", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
